---
- name: File Module
  hosts: all
  become: true
  tasks:
    - name: Creating a file
      file:
        path: /tmp/newFile.txt
        state: touch
        owner: ritik
        group: ritik
        mode: ugo=rwx
    - name: Creating a directory
      file:
        path: /tmp/myFolder
        state: directory
        owner: ritik
        mode: ugo=r
