---
- hosts: localhost
  connection: local

  tasks:
  - name: create ec2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "prod-ssh-key"
      # vpc_subnet_id: subnet-013744e41e8088axx
      instance_type: t2.micro
      security_group: default
      region: ap-south-1
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        environment: "{{ item.name }}"
      loop: 
        - { image: "AMI-ID for AWS-Linux", name: "manage-node-1" }
        - { image: "AMI-ID for ubuntu-1", name: "manage-node-2" }
        - { image: "AMI-ID for ubuntu-2", name: "manage-node-3" }
